sudo: required
language: java

services:
    - docker

env:
    global:
        - RUSHHOUR_VER=1.0-SNAPSHOT
        - CC_TEST_REPORTER_ID=60091ab280e51b0abd3d8b58d1a6d909f30be3b2a7a366aa8234eb3205bb7abf
        - JACOCO_SOURCE_PATH=src/main/java
        - APP_URL=http://localhost/RushHourGame-$RUSHHOUR_VER

addons:
    chrome: stable

before_install:
    # for coverage
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

    # for unit test
    - docker network create rushhour-net-ut
    - pushd docker/unit-test
    - mkdir -m 777 -p log/db data
    - docker-compose up -d --build
    - popd

    # for integration test
    - docker network create rushhour-net-it
    - pushd docker/integration-test
    - mkdir -m 777 -p log/db log/aps log/web data autodeploy conf/aps conf/web
    - docker-compose up -d --build
    - sleep 60
    - ls -laR docker/integration-test/conf
    - cat docker/integration-test/conf/web/default.conf
    - popd
    
install:
    - npm install
    - npx gulp  
    - npx gulp karma
    - mvn install -P development -q -Dmaven.javadoc.skip=true -B
    
    # unit test
    - mvn test jacoco:report coveralls:report -P development -q -B

    # integration test
    - mvn clean install -P integration-test -Dit.skip=true -Drushhour.host=integrationtest_rushhour-web_1 -Drushhour.port=80
    - cp target/*.war docker/integration-test/autodeploy
    - sleep 30
    - curl -X GET $APP_URL/gm?op=start
    - mvn integration-test verify -P integration-test -B -Drushhour.host=integrationtest_rushhour-web_1 -Drushhour.port=80
  
after_script:
    - tail -n 500 docker/integration-test/log/aps/server.log
    - ./cc-test-reporter format-coverage -t jacoco -o coverage/codeclimate.1.json target/site/jacoco/jacoco.xml
    - ./cc-test-reporter format-coverage -t lcov   -o coverage/codeclimate.2.json target/jscoverage/lcov/lcov.info
    - ./cc-test-reporter sum-coverage -p 2 coverage/codeclimate.*.json
    - ./cc-test-reporter upload-coverage 
