version: '3'

networks:
  default:
    external:
      name: rushhour-net

services:
    rushhour-db: 
        image: mariadb
        command: mysqld --character-set-server=utf8
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_USER}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - "${LOG_DIR}/db:/var/log/mysql"
            - "${DB_DATADIR}:/var/lib/mysql"
        ports:
            - "${DB_PORT}:3306"
    rushhour-aps:
        build: "./aps"
        image: rushhour-payara
        environment:
            ADMIN_USER: ${DAS_USER}
            ADMIN_PASSWORD: ${DAS_PASSWORD}
            DBHOST: rushhour-db
            DBPORT: 3306
            DBDATABASE: ${DB_USER}
            DBUSER: ${DB_USER}
            DBPASSWORD: ${DB_PASSWORD}
        volumes:
            - "${APS_CONFDIR}:/opt/payara5/conf"
            - "${APS_APPDIR}:/opt/payara5/glassfish/domains/domain1/autodeploy"
            - "${LOG_DIR}/aps:/opt/payara5/glassfish/domains/domain1/logs"
        ports:
            - "${DAS_PORT}:4848"
            - "${APS_PORT}:8080"
        links:
            - rushhour-db
    rushhour-web:
        build: 
            context: ./web 
            args:
                HOSTNAME: rushhour-web
                APS_HOST: rushhour-aps
                APS_PORT: 8080
                APNAME: ${APP_NAME}
        image: rushhour-nginx
        volumes:
            - "${LOG_DIR}/web:/var/log/nginx"
        ports:
            - "${WEB_PORT}:80"
        depends_on:
            - rushhour-aps
        links:
            - rushhour-aps