version: '3'

networks:
  default:
    external:
      name: rushhour-net-ut

services:
    rushhour-db: 
        build: "./db"
        image: rushhour-mariadb-ut
        command: mysqld --character-set-server=utf8
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_USER}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            TZ: JST-9
        volumes:
            - "${LOG_DIR}/db:/var/log/mysql"
            - "${DB_DATADIR}:/var/lib/mysql"
        ports:
            - "${DB_PORT}:3306"